### ISSUE TITLE
Add ability to choose what to use - rsync, regular copy or don't copy at all

### ISSUE THREAD

**Issue by igormukhingmailcom** [kosssi/ansible-role-apache#10]
Hi.

```
# defaults/main.yml
# Store type 
#1. Remote (default) - copy from remote server
apache_ssl_key_store_type: remote
#2. Local - copy from local machine to server
# apache_ssl_key_store_type: local
#3. None - don't copy certificates - it was copied before to proper location on server 
# apache_ssl_key_store_type: none
```

```
# tasks/vhost.yml
- name: Copy key from remote
  command: rsync -i --checksum "{{apache_ssl_key_store}}/{{item.1.key_file}}" "{{apache_ssl_path}}/{{item.1.key_file}}"
  when: ... and apache_ssl_key_store_type=='remote'

- name: Copy key from local
  copy: 
    src: "{{apache_ssl_key_store}}/{{item.1.key_file}}" 
    dest: "{{apache_ssl_path}}/{{item.1.key_file}}"
  when: ... and apache_ssl_key_store_type=='local'
```

WDYT, @kosssi?
